### PR TITLE
Fix missing IDATChunks of default/first frame on save

### PR DESCRIPTION
**Pull request by Gl0**
Force correct sequence numbers
Allow not animated images in AnimatedPictureBox

### CODE REVIEW

**Comment by Bungalow12** [comment]
I’d love to see your export work. Is it something yo have on your GitHub?
Anyway thanks for contributing to this!

**Comment by Gl0** [comment]
Will publish atf->png part, but will leave assembling textures into single animation private, since it use a lot of code related to specific game implementation (to get texture offsets you need to proceed through actual game login and parse it's source code - don't think publishing such things is a good idea)
Result is look like 
export

**Comment by Bungalow12** [comment]
That’s awesome. I totally understand leaving off game specific stuff. I’m happy this project could help.

**Comment by Gl0** [comment]
https://github.com/Gl0/atf2png

**Pull request merged**
